### ISSUE TITLE
Android8.0报 bad token

### ISSUE THREAD

**Issue by chen2174471** [yhaolpz/FloatWindow#4]
Process: com.example.yhao.fixedfloatwindow, PID: 2179
                                                                                 java.lang.RuntimeException: Unable to resume activity {com.example.yhao.fixedfloatwindow/com.example.yhao.floatwindow.A_Activity}: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@da7110b -- permission denied for window type 2002
                                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3645)
                                                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685)
                                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898)
                                                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                  Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@da7110b -- permission denied for window type 2002
                                                                                     at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
                                                                                     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                                     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                                     at com.yhao.floatwindow.FloatPhone.init(FloatPhone.java:55)
                                                                                     at com.yhao.floatwindow.IFloatWindowImpl.show(IFloatWindowImpl.java:70)
                                                                                     at com.yhao.floatwindow.IFloatWindowImpl$1.onShow(IFloatWindowImpl.java:52)
                                                                                     at com.yhao.floatwindow.FloatLifecycle.onActivityResumed(FloatLifecycle.java:62)
                                                                                     at android.app.Application.dispatchActivityResumed(Application.java:216)
                                                                                     at android.app.Activity.onResume(Activity.java:1312)
                                                                                     at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:437)
                                                                                     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
                                                                                     at android.app.Activity.performResume(Activity.java:7079)
                                                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)

**Comment by yhaolpz** [comment]
@chen2174471  v1.0.7 已适配8.0
